In [ ]:
import tensorflow as tf
a = 3
# Create a variable.
w = tf.Variable([[0.5,1.0]])
x = tf.Variable([[2.0],[1.0]]) 

y = tf.matmul(w, x)  


#variables have to be explicitly initialized before you can run Ops
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    print (y.eval())

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


[[2.]]


In [11]:
# float32
tensor=tf.zeros([3, 4], tf.float32)
# ==> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

# 'tensor' is [[1, 2, 3], [4, 5, 6]]
tf.zeros_like(tensor) 
# ==> [[0, 0, 0], [0, 0, 0]]
tf.ones([2, 3], tf.float32) 
# ==> [[1, 1, 1], [1, 1, 1]]

# 'tensor' is [[1, 2, 3], [4, 5, 6]]
tf.ones_like(tensor) 
# ==> [[1, 1, 1], [1, 1, 1]]

# Constant 1-D Tensor populated with value list.
tensor = tf.constant([1, 2, 3, 4, 5, 6, 7])
# => [1 2 3 4 5 6 7]

# Constant 2-D tensor populated with scalar value -1.
# tensor = tf.constant(-1.0, shape=[2, 3]) 
# => [[-1. -1. -1.]
#    [-1. -1. -1.]]

tf.linspace(10.0, 12.0, 3, name="linspace")
# => [ 10.0  11.0  12.0]

# 'start' is 3
# 'limit' is 18
# 'delta' is 3
# tf.range(start, limit, delta) 
# ==> [3, 6, 9, 12, 15]

<tf.Tensor 'linspace_1:0' shape=(3,) dtype=float32>

In [12]:
norm = tf.random_normal([2, 3], mean=-1, stddev=4)

# Shuffle the first dimension of a tensor
c = tf.constant([[1, 2], [3, 4], [5, 6]])
shuff = tf.random_shuffle(c)

# Each time we run these ops, different results are generated
sess = tf.Session()
print (sess.run(norm))
print (sess.run(shuff))

[[-2.1203103 -4.0951033 -2.4508545]
 [-2.083967  -3.0543349 -1.4332198]]
[[5 6]
 [3 4]
 [1 2]]


Session 1
[ 0.31830382]
[ 0.66478765]
[ 1.00602591]
[ 0.28635645]
Session 2
[ 0.53769958]
[ 0.82813144]
[-0.83388585]
[ 0.32747623]


In [13]:
state = tf.Variable(0)
new_value = tf.add(state, tf.constant(1))
update = tf.assign(state, new_value)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(state))    
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

0
1
2
3


In [14]:
#tf.train.Saver
w = tf.Variable([[0.5,1.0]])
x = tf.Variable([[2.0],[1.0]])
y = tf.matmul(w, x)
init_op = tf.global_variables_initializer()
saver = tf.train.Saver()
with tf.Session() as sess:
    sess.run(init_op)
# Do some work with the model.
# Save the variables to disk.
    save_path = saver.save(sess, "tmp/model/test")
    print ("Model saved in file: ", save_path)


Model saved in file:  tmp/model/test


In [15]:
import numpy as np
a = np.zeros((3,3))
ta = tf.convert_to_tensor(a)
with tf.Session() as sess:
     print(sess.run(ta))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)
output = tf.multiply(input1, input2)
with tf.Session() as sess:
    print(sess.run([output], feed_dict={input1:[7.], input2:[2.]}))

[array([14.], dtype=float32)]
